apiVersion: fintlabs.no/v1alpha1
kind: FintClient
metadata:
  name: flais-test-client
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: test-adapter
    app.kubernetes.io/instance: test-adapter_flais_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: adapter
    app.kubernetes.io/part-of: internal
    fintlabs.no/team: flais
    fintlabs.no/org-id: fintlabs-no

spec:
  orgId: fintlabs.no
  note: Dette er en test. Nu kjör vi!!
  components:
    - administrasjon_personal
    - utdanning_elev

