apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - exclude-kafka.yaml
patches:
  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-alpha-vault/items/finterator"
    target:
      kind: OnePasswordItem
      name: finterator
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: fint.application-id
          value: finterator-alpha
    target:
      kind: Deployment
      name: finterator